---
# tasks file for docker_centos
#

- name: Update package manager cache
  yum:
    name: '*'
    state: latest
  register: update
  ignore_errors: true

- name: cheking eroor while yum update
  debug:
    var: update.stderr_lines
    
- name: Install prerequisites for CentOS
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
  register: prerequesties
  ignore_errors: yes

- name: checking error while installing prequisites
  debug:
    var: prerequesties.stderr

- name: Add Docker repository
  yum_repository:
    name: docker
    description: Docker
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes
  register: repo

- name: checking errors while adding repo
  debug:
    var: repo.stderr

- name: enabling repo
  shell: |
    yum clean all
    yum makecache
  register: shell
  ignore_errors: true

- name: cheking errors while enabling repo
  debug:
    var: shell.stderr_lines

- name: repo adding output
  debug:
    var: shell.stdout_lines

- name: Install Docker
  yum:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
  register: install
  ignore_errors: true

- name: checking error while docker installation
  debug:
    var: install.stderr

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: yes
  register: start

- name: cheking errors while starting docker
  debug:
    var: start.stderr
