---
# tasks file for docker_centos
#

- name: Update package manager cache
  yum:
    name: '*'
    state: latest
  register: update

- name: cheking eroor while yum update
  debug:
    var: update.stderr
    
- name: Install prerequisites for CentOS
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
  register: prerequesties

- name: checking error while installing prequisites
  debug:
    var: prerequesties.stderr

- name: Add Docker repository
  yum_repository:
    name: docker
    description: Docker
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    gpgcheck: yes
    enabled: yes
    gpgkey: "060A 61C5 1B55 8A7F 742B 77AA C52F EB6B 621E 9F35"
  register: repo

- name: checking errors while adding repo
  debug:
    var: repo.stderr

- name: Install Docker
  yum:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
  register: install

- name: checking error while docker installation
  debug:
    var: install.stderr

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: yes
  register: start

- name: cheking errors while starting docker
  debug:
    var: start.stderr
